version: '3.5'
services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=postgres

    healthcheck:
      test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
      interval: 10s
      timeout: 2s
      retries: 10

    ports:
      - 5432:5432  
    volumes: 
      - db:/var/lib/postgresql/data

  nocodb:
    depends_on:
      db:
        condition: service_healthy
    image: nocodb/nocodb:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
      # host.docker.internal lets the container access our machine's localhost
      # NC_DB: "pg://host.docker.internal:5432?u=postgres&p=postgress&d=postgres"
      # Alternately we use the name of the container hosting the db
      NC_DB: "pg://postgres:5432?u=postgres&p=postgress&d=postgres"


volumes:
  db:
    driver: local