version: '3.5'
services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432  
    volumes: 
      - db:/var/lib/postgresql/data

    healthcheck:
      test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
      interval: 10s
      timeout: 2s
      retries: 10

  baserow:
    depends_on:
      db:
        condition: service_healthy
    container_name: baserow
    image: baserow/baserow:1.11.0
    environment:
      BASEROW_PUBLIC_URL: 'http://localhost'
      # DATABASE_HOST: host.docker.internal # lets the container access our machine's localhost
      DATABASE_HOST: postgres # Name of the db container
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgress
      DATABASE_PORT: 5432
      DISABLE_VOLUME_CHECK: "yes" # we're using the postgres volume to persist data
    ports:
      - "80:80"
      - "443:443"

volumes:
  db:
    driver: local