version: '3.9'
services:
  webserver:
    build:
      context: .
    container_name: take_home
    image: python:3.9.2
    ports:
      - 5000:5000

    # Need to wait for db to spin up  
    depends_on:
      db:
        condition: service_healthy
      
  db:
    container_name: flask-backend-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432  
    volumes: 
      - db:/var/lib/postgresql/data

    # Need healthcheck or else flask will try to hit the database before it's ready
    healthcheck:
      test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
      interval: 10s
      timeout: 2s
      retries: 10

volumes:
  db:
    driver: local